### ISSUE TITLE
Missing dependencies cause install failure

### ISSUE THREAD

**Issue by jdsutton7** [omegaui/linux-voice-control#20]
`src/pyaudio/device_api.c:9:10: fatal error: portaudio.h: No such file or directory`

Fixed with:
`sudo apt install portaudio19-dev python3-pyaudio`

OS: Linux Mint 21.3 x86_64 
Kernel: 5.15.0-122-generic

**Comment by jdsutton7** [comment]
Package `libmpv-dev` is also missing from dependencies:

```
Traceback (most recent call last):
  File "/home/family/lvc-bin/main.py", line 19, in <module>
    import chatgpt_port
  File "/home/family/lvc-bin/chatgpt_port.py", line 9, in <module>
    import command_manager
  File "/home/family/lvc-bin/command_manager.py", line 19, in <module>
    from voice_feedback import give_execution_feedback, speak, give_exiting_feedback
  File "/home/family/lvc-bin/voice_feedback.py", line 10, in <module>
    import mpv
  File "/home/family/.local/lib/python3.10/site-packages/mpv.py", line 11, in <module>
    backend = CDLL('libmpv.so')
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmpv.so: cannot open shared object file: No such file or directory
```

**Comment by omegaui** [comment]
does `sudo apt-get install libmpv-dev` works?

**Comment by omegaui** [comment]
@jdsutton7 also check the build from source section in Readme, it contains instructions for fixing known issues while installing.
